[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "mirror-builder"
authors = [
    {name = "Mark McLoughlin", email="markmc@redhat.com"},
    {name = "Doug Hellmann", email="dhellmann@redhat.com"},
]
description = "Wheel mirror builder"
dynamic = ["version"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: Implementation :: CPython",
    "Topic :: Utilities",
]

requires-python = ">=3.9"

dependencies = [
    "html5lib",
    "packaging",
    "pyproject_hooks",
    "python-pypi-mirror",
    "requests",
    "resolvelib",
    "tomli",
]

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-cov",
    "coverage!=4.4,>=4.0",
]

[tool.setuptools]
packages = [
    "mirror_builder",
    "mirror_builder.overrides",
    "mirror_builder.patches",
]

[tool.setuptools.package-data]
"mirror_builder.patches" = ["*.patch"]
